# Generated by Django 4.2.4 on 2023-09-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='сессия для оплаты'),
        ),
    ]
