# Generated by Django 4.2.4 on 2023-08-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='превью')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ('-title',),
            },
        ),
    ]
