# Generated by Django 4.2.4 on 2023-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(to='lesson.lesson', verbose_name='урок_курса'),
        ),
    ]
