# Generated by Django 4.2.4 on 2023-09-18 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='changed',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата изменения'),
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='дата добавления'),
            preserve_default=False,
        ),
    ]
